name: BitcoinWorld
favicon: null
layout_spectrum: 0.45231148949824274
typography_spectrum: 0.1346833985298872
title: Bringing you the latest news and information about BTC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#676767'
    - '#d98c22'
    - '#c9c9c9'
  brandStrength: 0.2979593425989151
  lightness: 0.2265321323648095
  saturation: 0.45361812761984766
  rhythmicContrast: 0.75
purpose: []
