name: BitcoinWorld
favicon: null
layout_spectrum: 0.45231148949824274
typography_spectrum: 0.1346833985298872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2979593425989151
  lightness: 0.2265321323648095
  saturation: 0.45361812761984766
  rhythmicContrast: 0.7097899210639298
purpose: []
